# A string used to distinguish different Supabase projects on the same host.
project_id = "knowembed"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173"]

[functions.chat]
verify_jwt = true

[functions.ingest-document]
verify_jwt = true

[functions.publish-bot]
verify_jwt = true

[functions.public-chat]
verify_jwt = false

[functions.public-bot]
verify_jwt = false
